services:
  boilerplate:
    image: ${CONTAINER_NAME}
    container_name: temp_${CONTAINER_NAME}
    build:
      context: .
      target: final
    environment:
      - LEVEL=${LEVEL:-1}  # Added default value
    volumes:
      - ./testcases:/usr/src/app/testcases
      - ./src:/usr/src/app/src # UNCOMMENT THIS FOR LOCAL TESTING
      
      - ./output:/usr/src/app/output
